### ISSUE TITLE
[BUG] Update cadence in Next scaffold

### ISSUE THREAD

**Issue by tombeckenham** [chasefleming/fcl-next-scaffold#11]
The cadence scripts in this repo are out of date and don't work if run out of the box.

* The smart contract needs to use `access (all)` instead of `pub`
* The update script needs to take `&Account` instead of `AuthAccount`

**Comment by chasefleming** [comment]
Thanks @tombeckenham . I will update it.

**Comment by chasefleming** [comment]
This will also be upgraded next release of the CLI: https://github.com/onflow/flow-cli/pull/1828
